version: "3.8"
services:
  api:
    container_name: api-mongodb
    build: .
    command: npm run dev
    restart: unless-stopped
    env_file:
      - /.env
    environment:
      - DB_URL=mongodb://mongo:27017/api
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_dbv:/data/db/
    environment:
      - MONGO_INITDB_DATABASE=api
    ports:
      - "27017:27017"
volumes:
  mongo_dbv: {}
